name:                server
version:             0.1.0.0
github:              "githubuser/server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

# maybe should remove TemplateHaskell, QuasiQuotes later!
default-extensions: OverloadedStrings, TemplateHaskell, QuasiQuotes

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- warp
- wai
- http-types
- postgresql-simple
- postgresql-simple-migration
- cryptohash-md5
- ansi-terminal
- text
- aeson
- split
# - exceptions
# - exception-transformers
- transformers
- mtl
- hspec
- QuickCheck
- containers
- aeson-pretty
- neat-interpolation
- time
library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
